import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layouts/appSidebar";
import Navbar from "@/components/layouts/navbar";
import type { NextRequest } from 'next/server'
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies()
  const token = cookieStore.get('token')?.value
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {!token ? (
          <main className=" bg-gray-100 flex-1 w-full overflow-hidden">
            <div className="p-2 flex flex-col gap-8">
              {children}
            </div>
          </main>
        ) : (
          <SidebarProvider>
            <AppSidebar />
            <main className=" bg-gray-100 flex-1 w-full overflow-hidden">
              <Navbar />
              <div className="p-2 flex flex-col gap-8">
                {children}
              </div>
            </main>
          </SidebarProvider>
        )}
      </body>
    </html>
  );
}
